### ISSUE TITLE
Base Class FFh (Vendor Specific) USB viewer

### ISSUE THREAD

**Issue by momosh13** [PaulStoffregen/USBHost_t36#133]
Hi
I'm trying to get and view info from Base Class FFh (Vendor Specific) USB device, just like USBHost_viewer, help need it.
Thank you in advance

**Comment by PaulStoffregen** [comment]
Ask on the forum
https://forum.pjrc.com/index.php

this place is only for reporting software defects

**Comment by momosh13** [comment]
Hi
I'm trying to reset my password with pjrc forume for tree days and no luck, please help me, my email is: ***@***.***


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by PaulStoffregen** [comment]
Microsoft's servers are rejecting forum messages for all Hotmail and Outlook accounts.  Use a different email for the forum.
