### ISSUE TITLE
No issues, Just a big THANK YOU!!!

### ISSUE THREAD

**Issue by badonj001** [PaulStoffregen/USBHost_t36#34]
USBHost_t36-master\USBHost_t36-master\examples\Test\SerialTest\SerialTest.ino

Got my project going faster than I thought it would. I serioulsly appreciate it!!!

I also used TallDogs custom Breakout for the Teensy 3.6, make development so much easier!
https://www.tindie.com/products/loglow/teensy-3536-breakout-revision-a-due/

**Comment by PaulStoffregen** [comment]
:)
