### ISSUE TITLE
Not working on Teensy 4.1 

### ISSUE THREAD

**Issue by akinsibay** [PaulStoffregen/USBHost_t36#41]
Hi,
I have a Teensy 4.1 board. I would like to use 5V and GND pins using USB Host.
I have downloaded USBHOST_T36 library and uploaded my 4.1 board but throwed an error below:

#error "USBHost_t36 only works with Teensy 3.6. Please select it in Tools > Boards"
I need 5V for my project. How can i receive 5V from USB host pin or another pins?

**Comment by PaulStoffregen** [comment]
Let's discuss on the forum.  Github issues not meant only for reporting software defects, not for support.

https://forum.pjrc.com/threads/64074-USBHOST_T36-library-is-not-working-on-Teensy-4-1-Board
