### ISSUE TITLE
Will be BT is support?

### ISSUE THREAD

**Issue by Shootingmaker** [PaulStoffregen/USBHost_t36#5]
Now PS4 support  with USB Cabled ONLY.
Will be BT dongle support?

Like as,
<PS4BT.h>
https://github.com/felis/USB_Host_Shield_2.0/blob/master/examples/Bluetooth/PS4BT/PS4BT.ino

**Comment by PaulStoffregen** [comment]
Ask here:

https://forum.pjrc.com/forums/4-Suggestions-amp-Bug-Reports

This issue tracking is only for reporting confirmed bugs.
