### ISSUE TITLE
Serial support for dtr and rts missing

### ISSUE THREAD

**Issue by FrankBoesing** [PaulStoffregen/USBHost_t36#65]
Cann you add it, please?

The emualtion is not complete without them (and I need them...)

**Comment by PaulStoffregen** [comment]
Kurt did most of the serial driver work.  Probably best to discuss on the forum.

These special bits are handled differently by each protocol, so it's not just 1 thing to add.  I'm sure it can be done, just not quick & easy.  Best to at least mention which USB-serial you're using.

**Comment by FrankBoesing** [comment]
Thank you. I asked Kurt.
