### ISSUE TITLE
Doesn't compile for me

### ISSUE THREAD

**Issue by nello** [PaulStoffregen/USBHost_t36#90]
I'm trying to use Teensyduino as a USB host for HID devices and having some problems with hubs, so thought I would try the latest version. I get this error:

In file included from /Applications/Teensyduino.app/Contents/Java/hardware/teensy/avr/libraries/USBHost_t36/examples/Joystick/Joystick.ino:5:0: /Applications/Teensyduino.app/Contents/Java/hardware/teensy/avr/libraries/USBHost_t36/USBHost_t36.h:2095:66: error: expected class-name before '{' token class USBDrive : public USBDriver, public FsBlockDeviceInterface { ^ Error compiling for board Teensy 4.1.

The Joystick.ino is the example that comes with Teensyduino.

**Comment by PaulStoffregen** [comment]
Depends on latest libraries.  Easiest way to get everything updated is here:

https://forum.pjrc.com/threads/70196-Teensyduino-1-57-Beta-1

**Comment by nello** [comment]
Thanks!
